---
# File: site.yml - Example Vault server playbook (Filesystem storage)

- name: Install Vault
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  roles:
    - role: ansible-community.ansible-vault
      vault_api_addr: "https://vault-dr.tools.dcsg.com:8200"
      vault_version: "1.5.4"
      vault_backend: raft
      vault_install_remotely: true
      vault_privileged_install: true
      vault_service_reload: true
      vault_tls_cert_file: cert.cer
      vault_tls_key_file: cert.key
      vault_tls_ca_file: cert.ca
      vault_tls_disable: 0